In [19]:
df = pd.read_csv('D:\\Atom\\Matlab\\论文\\识别结果\\result.csv')

In [20]:
matl_cnt = len(df['MATERIALS'].unique())
pos_cnt = len(df['POSITION'].unique())
len(df)

160

In [34]:
df['POSITION'].unique()

array([ 30,  33,  36,  39,  42,  45,  48,  51,  54,  57,  60,  63,  66,
        69,  72,  75,  78,  81,  84,  87,  90,  93,  96,  99, 102, 105,
       108, 111, 114, 117, 120, 123, 126, 129, 132, 135, 138, 141, 144,
       147], dtype=int64)

In [21]:
result = np.zeros((len(df), len(df)))
result.fill(np.nan)
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 160 entries, 0 to 159
Data columns (total 4 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   POSITION     160 non-null    int64  
 1   MATERIALS    160 non-null    object 
 2   GUESSED POS  159 non-null    float64
 3   GUESSED      159 non-null    object 
dtypes: float64(1), int64(1), object(2)
memory usage: 5.1+ KB


In [22]:
d = {'vinegar': 0, 'empty': 1, 'water': 2, 'oil2': 3}
for index, row in df.iterrows():
    ans = 0
    if np.isnan(row['GUESSED POS']):
        continue
    if row['POSITION'] == row['GUESSED POS']:
        ans += 50
    if row['MATERIALS'] == row['GUESSED']:
        ans += 50
    
    guessed = int((row['GUESSED POS']-30)/3 + d[row['GUESSED']]*40)
    result[index][guessed] = ans

In [23]:
import scipy.io
scipy.io.savemat('test.mat', {'mydata': result})

In [24]:
for name, group in df.groupby('MATERIALS'):
    print(name, len(group))

empty 40
oil2 40
vinegar 40
water 40


In [25]:
must = np.arange(30, 150, 3)
actual = df.groupby('MATERIALS').get_group('oil2')['POSITION']
np.setdiff1d(must, actual)

array([], dtype=int32)

In [26]:
df[df['GUESSED'].isnull()]

POSITION MATERIALS  GUESSED POS GUESSED
123        39      oil2          NaN     NaN

In [27]:
df['MATERIALS'].unique()

array(['vinegar', 'empty', 'water', 'oil2'], dtype=object)

In [28]:
result[35,:]

array([nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
       nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
       nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
       nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
       nan, nan, nan, nan, nan, nan, nan,  0., nan, nan, nan, nan, nan,
       nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
       nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
       nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
       nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
       nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
       nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
       nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
       nan, nan, nan, nan])

In [12]:
result

array([[100.,  nan,  nan, ...,  nan,  nan,  nan],
       [ nan,  50.,  nan, ...,  nan,  nan,  nan],
       [ nan,  nan, 100., ...,  nan,  nan,  nan],
       ...,
       [ nan,  nan,  nan, ...,  nan,  nan,  nan],
       [ nan,  nan,  nan, ...,  nan,  nan,  nan],
       [ nan,  nan,  nan, ...,  nan,  nan,  nan]])

In [13]:
result.shape

(160, 160)

In [14]:
(result == 100).sum()

118

In [15]:
(result == 50).sum()

17

In [16]:
(result == 0).sum()

24

In [17]:
vinegar = result[0:31, 0:31]
empty = result[40:80, 40:80]
water = result[80:120, 80:120]
oil = result[120:160, 120:160]

In [39]:
for i in range(0, 4):
    print((result[i*40: i*40+31, i*40: i*40+31] >= 50).sum())

31
31
31
30


<ipython-input-39-7085e6c33d2d>:2: RuntimeWarning: invalid value encountered in greater_equal
  print((result[i*40: i*40+31, i*40: i*40+31] >= 50).sum())


In [30]:
np.set_printoptions(threshold=np.inf)