In [2]:
import os
import numpy as np
import pandas as pd
import sys
sys.path.extend(['d:\\atom\\python'])
import data_manager as dm
import io_helper as io

In [3]:
df_phase = pd.DataFrame()
df_rssi = pd.DataFrame()

In [4]:
def calculate_diff(dfs):
    phase = [{}, {}]
    rssi = [{}, {}]

    i = 0
    for df in dfs:
        records = df.to_dict('records')
        for record in records:
            channel = record['CHANNEL']
            phase[i][channel] = record['PHASE']
            rssi[i][channel] = record['RSSI']
        i += 1

    diff_phase, diff_rssi = {}, {}
    for channel in dm.channels:
        if channel not in phase[0] or channel not in phase[1]:
            diff_phase[channel] = np.NaN
            diff_rssi[channel] = np.NaN
            continue
        diff_phase[channel] = phase[1][channel] - phase[0][channel]
        diff_rssi[channel] = rssi[1][channel] - phase[0][channel]

    return diff_phase, diff_rssi

In [5]:
for dist in dm.dists:
    df1 = io.import_from_file(os.path.join(dm.folder_liquid, str(dist) + 'cm_empty.csv'), dm.epc_liquid)
    df2 = io.import_from_file(os.path.join(dm.folder_liquid, str(dist) + 'cm_vinegar.csv'), dm.epc_liquid)

    if df1.empty or df2.empty:
        continue
    
    diff_phase, diff_rssi = calculate_diff([df1, df2])
    df_phase[dist] = diff_phase.values()
    df_rssi[dist] = diff_rssi.values()

In [6]:
df_phase.corr()

12        13        14        15        18        21        24  \
12  1.000000  0.491445  0.086115 -0.385294 -0.205895 -0.216212 -0.280563   
13  0.491445  1.000000  0.556406  0.139869 -0.354887 -0.342200 -0.389476   
14  0.086115  0.556406  1.000000  0.501916 -0.139898 -0.314083 -0.369744   
15 -0.385294  0.139869  0.501916  1.000000  0.250014 -0.142852 -0.319692   
18 -0.205895 -0.354887 -0.139898  0.250014  1.000000  0.489567  0.170622   
21 -0.216212 -0.342200 -0.314083 -0.142852  0.489567  1.000000  0.594284   
24 -0.280563 -0.389476 -0.369744 -0.319692  0.170622  0.594284  1.000000   
27 -0.334501 -0.305031 -0.338489 -0.322779 -0.375106 -0.022400  0.367856   
30 -0.017199 -0.321210 -0.353023 -0.330847 -0.374774 -0.396666 -0.332194   
36 -0.161728  0.339924  0.693996  0.789180  0.200970 -0.111883 -0.401499   
39 -0.250818 -0.379285 -0.242177  0.169681  0.829665  0.673678  0.314206   
42 -0.237354 -0.233184 -0.339658 -0.264822 -0.051405  0.469931  0.723050   
78 -0.495751 -0.326251 -0.065086  0.167697  0.169623  0.270239  0.605838   
81 -0.413437 -0.377129 -0.339059 -0.159818 -0.206287 -0.260902  0.147472   
84 -0.699664  0.195503 -0.082347  0.253113 -0.373788 -0.476404 -0.584985   
90  0.464918 -0.110977 -0.173788 -0.156411 -0.086522 -0.186399 -0.112104   
93 -0.108234 -0.075922 -0.099414 -0.168788 -0.254584  0.057880  0.453387   

          27        30        36        39        42        78        81  \
12 -0.334501 -0.017199 -0.161728 -0.250818 -0.237354 -0.495751 -0.413437   
13 -0.305031 -0.321210  0.339924 -0.379285 -0.233184 -0.326251 -0.377129   
14 -0.338489 -0.353023  0.693996 -0.242177 -0.339658 -0.065086 -0.339059   
15 -0.322779 -0.330847  0.789180  0.169681 -0.264822  0.167697 -0.159818   
18 -0.375106 -0.374774  0.200970  0.829665 -0.051405  0.169623 -0.206287   
21 -0.022400 -0.396666 -0.111883  0.673678  0.469931  0.270239 -0.260902   
24  0.367856 -0.332194 -0.401499  0.314206  0.723050  0.605838  0.147472   
27  1.000000  0.323552 -0.436421 -0.324611  0.408622  0.295129  0.761003   
30  0.323552  1.000000 -0.400674 -0.409004 -0.361754 -0.349223  0.409089   
36 -0.436421 -0.400674  1.000000  0.104308 -0.279974  0.031638 -0.350618   
39 -0.324611 -0.409004  0.104308  1.000000  0.158133  0.259328 -0.290865   
42  0.408622 -0.361754 -0.279974  0.158133  1.000000  0.493042  0.213973   
78  0.295129 -0.349223  0.031638  0.259328  0.493042  1.000000  0.268939   
81  0.761003  0.409089 -0.350618 -0.290865  0.213973  0.268939  1.000000   
84  0.433983  0.831544  0.024957 -0.370187 -0.566050 -0.057140  0.393199   
90  0.210716  0.309666 -0.180635 -0.090189 -0.365935 -0.144012 -0.086557   
93  0.477424 -0.227329 -0.201178 -0.335058  0.611339  0.349210  0.444672   

          84        90        93  
12 -0.699664  0.464918 -0.108234  
13  0.195503 -0.110977 -0.075922  
14 -0.082347 -0.173788 -0.099414  
15  0.253113 -0.156411 -0.168788  
18 -0.373788 -0.086522 -0.254584  
21 -0.476404 -0.186399  0.057880  
24 -0.584985 -0.112104  0.453387  
27  0.433983  0.210716  0.477424  
30  0.831544  0.309666 -0.227329  
36  0.024957 -0.180635 -0.201178  
39 -0.370187 -0.090189 -0.335058  
42 -0.566050 -0.365935  0.611339  
78 -0.057140 -0.144012  0.349210  
81  0.393199 -0.086557  0.444672  
84  1.000000       NaN -0.598085  
90       NaN  1.000000  0.298464  
93 -0.598085  0.298464  1.000000

In [7]:
df_rssi.corr()

12        13        14        15        18        21        24  \
12  1.000000  0.492319  0.066605 -0.340071 -0.227338 -0.222979 -0.381849   
13  0.492319  1.000000  0.433345 -0.164447 -0.224252 -0.201259 -0.228565   
14  0.066605  0.433345  1.000000 -0.027384 -0.276772 -0.272868 -0.028888   
15 -0.340071 -0.164447 -0.027384  1.000000  0.004278 -0.138191 -0.003757   
18 -0.227338 -0.224252 -0.276772  0.004278  1.000000  0.374562 -0.150940   
21 -0.222979 -0.201259 -0.272868 -0.138191  0.374562  1.000000  0.083573   
24 -0.381849 -0.228565 -0.028888 -0.003757 -0.150940  0.083573  1.000000   
27 -0.219634 -0.281370 -0.125684  0.001140 -0.279511 -0.259915  0.111600   
30  0.326059  0.027138 -0.105752 -0.115475 -0.270654 -0.357569 -0.352041   
36 -0.005078  0.140628  0.294451  0.237559  0.162506 -0.151606 -0.189114   
39 -0.298440 -0.262616 -0.278482 -0.085864  0.743491  0.665206 -0.022023   
42 -0.289645 -0.297121 -0.219522 -0.124136  0.237290  0.473232  0.527619   
78 -0.384235 -0.321086 -0.137738 -0.168106  0.250556  0.204660  0.589089   
81 -0.296054 -0.332008 -0.106477  0.030371 -0.285564 -0.168925  0.089465   
84  0.762624  0.686735  0.626865  0.650760 -0.653820 -0.617569 -0.192806   
90  0.701901  0.348485 -0.034215 -0.427398 -0.421706 -0.655337 -0.854238   
93 -0.039094 -0.174226 -0.295396 -0.277334  0.225113  0.440258  0.270926   

          27        30        36        39        42        78        81  \
12 -0.219634  0.326059 -0.005078 -0.298440 -0.289645 -0.384235 -0.296054   
13 -0.281370  0.027138  0.140628 -0.262616 -0.297121 -0.321086 -0.332008   
14 -0.125684 -0.105752  0.294451 -0.278482 -0.219522 -0.137738 -0.106477   
15  0.001140 -0.115475  0.237559 -0.085864 -0.124136 -0.168106  0.030371   
18 -0.279511 -0.270654  0.162506  0.743491  0.237290  0.250556 -0.285564   
21 -0.259915 -0.357569 -0.151606  0.665206  0.473232  0.204660 -0.168925   
24  0.111600 -0.352041 -0.189114 -0.022023  0.527619  0.589089  0.089465   
27  1.000000  0.162848 -0.210147 -0.245009 -0.070075  0.167891  0.624402   
30  0.162848  1.000000 -0.044419 -0.394289 -0.300856 -0.341168  0.193751   
36 -0.210147 -0.044419  1.000000  0.020188 -0.045106  0.068841 -0.201683   
39 -0.245009 -0.394289  0.020188  1.000000  0.405126  0.243038 -0.242932   
42 -0.070075 -0.300856 -0.045106  0.405126  1.000000  0.533611 -0.134072   
78  0.167891 -0.341168  0.068841  0.243038  0.533611  1.000000  0.033377   
81  0.624402  0.193751 -0.201683 -0.242932 -0.134072  0.033377  1.000000   
84  0.918872  0.940251 -0.051953 -0.703081 -0.701215 -0.252770  0.864479   
90 -0.831582  0.508638  0.128375 -0.634902 -0.785079 -0.884700 -0.890296   
93  0.078268 -0.045227 -0.075041  0.354397  0.786778  0.445368 -0.091847   

          84        90        93  
12  0.762624  0.701901 -0.039094  
13  0.686735  0.348485 -0.174226  
14  0.626865 -0.034215 -0.295396  
15  0.650760 -0.427398 -0.277334  
18 -0.653820 -0.421706  0.225113  
21 -0.617569 -0.655337  0.440258  
24 -0.192806 -0.854238  0.270926  
27  0.918872 -0.831582  0.078268  
30  0.940251  0.508638 -0.045227  
36 -0.051953  0.128375 -0.075041  
39 -0.703081 -0.634902  0.354397  
42 -0.701215 -0.785079  0.786778  
78 -0.252770 -0.884700  0.445368  
81  0.864479 -0.890296 -0.091847  
84  1.000000       NaN -0.589437  
90       NaN  1.000000  0.197879  
93 -0.589437  0.197879  1.000000

In [10]:
from sklearn.decomposition import PCA

In [13]:
df_phase = df_phase.drop(columns=[84, 90, 93])

In [14]:
pca = PCA()
pca.fit(df_phase)

PCA()

In [15]:
pca.components_

array([[-0.18201508, -0.28769125, -0.27942976, -0.17570248,  0.03642692,
         0.21290146,  0.43997793,  0.3605145 ,  0.01966503, -0.26301162,
         0.10276073,  0.36056425,  0.3076635 ,  0.31648328],
       [ 0.07022838,  0.01251923, -0.08407048, -0.1864589 , -0.3361933 ,
        -0.32706598, -0.20983757,  0.30087916,  0.45715649, -0.21550958,
        -0.3971569 , -0.12984963, -0.20835793,  0.35365848],
       [ 0.33051096, -0.07840403, -0.33454077, -0.4244232 ,  0.11233166,
         0.22969294,  0.04712585, -0.22629527,  0.16472585, -0.38290034,
         0.17455708, -0.04908315, -0.39829847, -0.32937336],
       [ 0.2994084 ,  0.441859  ,  0.18153492, -0.22450013, -0.38119055,
        -0.00201975,  0.25939015,  0.08205745, -0.36294896, -0.08659574,
        -0.3119464 ,  0.36331557,  0.04456444, -0.20471319],
       [ 0.22436583, -0.12490111,  0.03747303, -0.11416954,  0.02372855,
        -0.39129492,  0.20703964, -0.33730652,  0.09523242, -0.23271713,
        -0.06860561, -0.32

In [16]:
pca.explained_variance_

array([34.1335625 , 27.92147439, 14.88501652, 12.66527854,  3.94014559,
        3.8532149 ,  2.76627841,  1.92706054,  1.72323046,  1.35879323,
        1.04123512,  0.98822495,  0.72505596,  0.53478122])

In [17]:
df_rssi = df_rssi.drop(columns=[84, 90, 93])

In [18]:
pca = PCA()
pca.fit(df_rssi)

PCA()

In [19]:
pca.components_

array([[ 2.60727109e-01,  1.87054733e-01,  1.06026855e-01,
         1.31896603e-02, -3.67698522e-01, -3.09615586e-01,
        -1.97758940e-01,  6.86663662e-02,  2.58748312e-01,
         3.83341379e-04, -4.61331664e-01, -4.43724710e-01,
        -3.56018139e-01,  8.55001994e-02],
       [ 2.77767495e-01,  2.23911729e-01,  2.79251710e-02,
        -2.26965388e-02,  3.56339198e-01,  1.40744185e-01,
        -3.87264721e-01, -3.98531502e-01, -1.77897834e-02,
         1.34840845e-01,  3.12944923e-01, -1.74366643e-01,
        -3.22218331e-01, -4.06404360e-01],
       [ 2.69291537e-01,  3.48499422e-01,  2.17108048e-01,
        -1.07895937e-01, -3.04789245e-01, -3.79210736e-02,
         3.53846111e-01, -2.93929053e-01, -1.96375962e-01,
         8.73822878e-02, -2.61353908e-01,  3.36683839e-01,
         2.13514708e-01, -4.09716179e-01],
       [ 4.02615377e-01, -6.33639143e-02, -3.03013406e-01,
        -3.15785521e-01, -1.72358836e-01,  3.10143336e-01,
        -3.19221743e-02,  4.45091304e-02,  3.

In [20]:
pca.explained_variance_

array([12.61472995,  7.3841929 ,  4.56022325,  3.28263635,  2.57755771,
        2.02513625,  1.60415598,  1.16365363,  1.11122561,  0.91586522,
        0.80882492,  0.69532181,  0.47792957,  0.43609251])