# Numpy: Numeric computing library

In [1]:
import numpy as np

make numeric computing more efficient(least amount of memory) and fast

In [2]:
np.int8

numpy.int8

Tab键无法自动补全是因为import语句还没有执行！

In [3]:
b = np.array([1, 1.2, 3])

In [4]:
type(b)

numpy.ndarray

In [5]:
b.dtype

dtype('float64')

In [7]:
b[[0, -1]]

array([1., 3.])

In [11]:
a = np.array([1, 2, 3], dtype=np.int8)

In [12]:
a.dtype

dtype('int8')

### Indexing and Slicing of Matrices

In [13]:
A = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

In [14]:
A[1][0]

4

In [15]:
A[1, 0]

4

In [16]:
A[:, :2]

array([[1, 2],
       [4, 5],
       [7, 8]])

In [20]:
A[2] = [7, 8, 9]

In [21]:
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

### Summary statistics

In [22]:
A.sum()

45

In [23]:
A.sum(axis = 0)

array([12, 15, 18])

In [24]:
A.sum(axis = 1)

array([ 6, 15, 24])

### Broadcasting and Vectorized operations

In [25]:
a = np.arange(4)

In [26]:
a

array([0, 1, 2, 3])

In [27]:
a + 10

array([10, 11, 12, 13])

In [28]:
a * 10

array([ 0, 10, 20, 30])

In [29]:
a

array([0, 1, 2, 3])

In [30]:
a += 100

In [31]:
a

array([100, 101, 102, 103])

In [32]:
l = [0, 1, 2, 3]

In [33]:
[i * 10 for i in l]

[0, 10, 20, 30]

In [34]:
a = np.arange(4)

In [35]:
a

array([0, 1, 2, 3])

In [36]:
b = np.array([10, 10, 10, 10])

In [37]:
b

array([10, 10, 10, 10])

In [38]:
a + b

array([10, 11, 12, 13])

In [39]:
a * b

array([ 0, 10, 20, 30])

### Boolean arrays

In [40]:
a = np.arange(4)

In [41]:
a

array([0, 1, 2, 3])

In [42]:
a[0], a[-1]

(0, 3)

In [43]:
a[[0, -1]]

array([0, 3])

In [45]:
a[[True, False, False, True]]

array([0, 3])

In [46]:
a >= 2

array([False, False,  True,  True])

In [47]:
a[a >= 2]

array([2, 3])

In [48]:
a

array([0, 1, 2, 3])

In [50]:
a.mean()

1.5

In [51]:
a[~(a > a.mean())]

array([0, 1])

In [52]:
a[(a == 0)|(a == 1)]

array([0, 1])

In [55]:
a[(a <= 2) & (a % 2 == 0)]

array([0, 2])

### Size of objects in Memory

In [56]:
import sys

In [59]:
sys.getsizeof(1)

28

In [60]:
sys.getsizeof(10**100)

72

In [62]:
np.dtype(float).itemsize

8

In [74]:
l = list(range(100000))

In [75]:
a = np.arange(100000)

In [76]:
%time np.sum(a ** 2)

Wall time: 995 µs


216474736

In [77]:
%time sum([x ** 2 for x in l])

Wall time: 48.9 ms


333328333350000

In [73]:
np.eye(3, 4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])