In [1]:
import pandas as pd

In [2]:
df = pd.DataFrame(data={'a': [1, 2, 2, 3], 'b': [3, 4, 5, 6]})

In [3]:
df

a  b
0  1  3
1  2  4
2  2  5
3  3  6

In [6]:
df.iloc[3]['a']

3

In [7]:
len(df)

4

In [9]:
import numpy as np
a = np.array([1, 2, 3])

In [10]:
a -= 2

In [11]:
a

array([-1,  0,  1])

In [41]:
np.array([1, 2, 3]) - 4

array([-3, -2, -1])

In [42]:
df['a'] - 1

0    0
1    1
2    1
3    2
Name: a, dtype: int64

In [48]:
np.mod(df['a'] - 1, 2)

0    0
1    1
2    1
3    0
Name: a, dtype: int64

In [38]:
(df['a'] - 2)**2 + (df['b'] - 3)**2

0     1
1     1
2     4
3    10
dtype: int64

In [22]:
from scipy.interpolate import Rbf

In [32]:
rbfi = Rbf([1, 2, 3], [1, 2, 3], [1, 4, 9], function='thin-plate')

In [34]:
rbfi(1.1, 1.1)

array(6.31649158)

In [50]:
np.arange(1, 10, 0.1)

array([1. , 1.1, 1.2, 1.3, 1.4, 1.5, 1.6, 1.7, 1.8, 1.9, 2. , 2.1, 2.2,
       2.3, 2.4, 2.5, 2.6, 2.7, 2.8, 2.9, 3. , 3.1, 3.2, 3.3, 3.4, 3.5,
       3.6, 3.7, 3.8, 3.9, 4. , 4.1, 4.2, 4.3, 4.4, 4.5, 4.6, 4.7, 4.8,
       4.9, 5. , 5.1, 5.2, 5.3, 5.4, 5.5, 5.6, 5.7, 5.8, 5.9, 6. , 6.1,
       6.2, 6.3, 6.4, 6.5, 6.6, 6.7, 6.8, 6.9, 7. , 7.1, 7.2, 7.3, 7.4,
       7.5, 7.6, 7.7, 7.8, 7.9, 8. , 8.1, 8.2, 8.3, 8.4, 8.5, 8.6, 8.7,
       8.8, 8.9, 9. , 9.1, 9.2, 9.3, 9.4, 9.5, 9.6, 9.7, 9.8, 9.9])

In [61]:
a = [30, 40, 50]
b = [902, 903, 904]

x, y = np.meshgrid(a, b)
z = a + b

In [69]:
len(z)

6

In [68]:
np.product(x.shape)

9

In [64]:
y

array([[902, 902, 902],
       [903, 903, 903],
       [904, 904, 904]])

In [65]:
z

[30, 40, 50, 902, 903, 904]

In [77]:
a = [5, 4, 10]
np.sort(a)

array([ 4,  5, 10])

In [74]:
a = np.argsort(a)
a = np.argsort(a)
a

array([1, 0, 2], dtype=int64)

In [76]:
a =[1, 2, 3, 4]
b = [1, 2, 3, 4]
np.add(a, b)

array([2, 4, 6, 8])

In [78]:
np.argmin(a)

1

In [79]:
a = np.array()
a.argmin()

TypeError: array() missing required argument 'object' (pos 1)